import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/* Small type record: scalars are plain i32, matrices are flat i32 arrays. */
final class TypeInfo {
    static final TypeInfo SCALAR = new TypeInfo(false, 0, 0);

    private final boolean matrix;
    private final int rows;
    private final int cols;

    TypeInfo(boolean matrix, int rows, int cols) {
        this.matrix = matrix;
        this.rows = rows;
        this.cols = cols;
    }

    boolean isMatrix() {
        return matrix;
    }

    boolean isScalar() {
        return !matrix;
    }

    int rows() {
        return rows;
    }

    int cols() {
        return cols;
    }

    int flatSize() {
        return rows * cols;
    }

    boolean sameShape(TypeInfo other) {
        return matrix == other.matrix && rows == other.rows && cols == other.cols;
    }
}

/* Tracks where a source variable lives in the generated LLVM IR. */
final class VarInfo {
    private final String name;
    private final TypeInfo type;
    private final String ptr;

    VarInfo(String name, TypeInfo type, String ptr) {
        this.name = name;
        this.type = type;
        this.ptr = ptr;
    }

    String name() {
        return name;
    }

    TypeInfo type() {
        return type;
    }

    String ptr() {
        return ptr;
    }
}

/* Lightweight handle for either a named matrix or a temporary matrix. */
final class MatrixRef {
    private final TypeInfo type;
    private final String ptr;

    MatrixRef(TypeInfo type, String ptr) {
        this.type = type;
        this.ptr = ptr;
    }

    TypeInfo type() {
        return type;
    }

    String ptr() {
        return ptr;
    }
}

/* LLVM string constants need both a name and their byte length. */
final class CString {
    private final String name;
    private final int length;

    CString(String name, int length) {
        this.name = name;
        this.length = length;
    }

    String gep() {
        return "getelementptr inbounds ([" + length + " x i8], ptr " + name + ", i64 0, i64 0)";
    }
}

abstract class Statement {
    abstract void generate(CodegenState state);
}

/* Expressions know their type and can emit either scalar or matrix IR. */
abstract class Expr {
    abstract TypeInfo type(CodegenState state);

    String simpleName() {
        return null;
    }

    String emitScalar(CodegenState state) {
        throw new RuntimeException("Expression is not a scalar");
    }

    MatrixRef emitMatrix(CodegenState state) {
        throw new RuntimeException("Expression is not a matrix");
    }
}

/* Shared state while lowering the parsed program into LLVM IR. */
final class CodegenState {
    /* Variables live here while the source program is translated. */
    private final Map<String, VarInfo> variables = new LinkedHashMap<String, VarInfo>();
    private final StringBuilder globals = new StringBuilder();
    private final StringBuilder body = new StringBuilder();
    private int tempCounter = 0;
    private int labelCounter = 0;
    private int stringCounter = 0;
    private int displayCounter = 0;

    private final CString fmtNum;
    private final CString fmtSpaceNum;
    private final CString emptyLine;

    CodegenState() {
        fmtNum = addCString("%d");
        fmtSpaceNum = addCString(" %d");
        emptyLine = addCString("");
        emitLabel("entry");
    }

    String buildIr() {
        emit("ret i32 0");
        StringBuilder out = new StringBuilder();
        out.append("; Generated by the MATLAB-like prototype compiler\n");
        out.append("declare i32 @printf(ptr noundef, ...)\n");
        out.append("declare i32 @puts(ptr noundef)\n\n");
        out.append(globals);
        out.append("\ndefine i32 @main() {\n");
        out.append(body);
        out.append("}\n");
        return out.toString();
    }

    /* Build one LLVM global string and remember how to reference it later. */
    private CString addCString(String text) {
        String name = "@.str." + stringCounter++;
        String escaped = escapeCString(text);
        int length = text.length() + 1;
        globals.append(name)
               .append(" = private unnamed_addr constant [")
               .append(length)
               .append(" x i8] c\"")
               .append(escaped)
               .append("\\00\"\n");
        return new CString(name, length);
    }

    /* Escape text so it is safe inside an LLVM c"..." string. */
    private static String escapeCString(String text) {
        StringBuilder escaped = new StringBuilder();
        for (int i = 0; i < text.length(); i++) {
            char c = text.charAt(i);
            switch (c) {
                case '\\':
                    escaped.append("\\5C");
                    break;
                case '"':
                    escaped.append("\\22");
                    break;
                case '\n':
                    escaped.append("\\0A");
                    break;
                case '\r':
                    escaped.append("\\0D");
                    break;
                case '\t':
                    escaped.append("\\09");
                    break;
                default:
                    if (c < 32 || c > 126) {
                        escaped.append(String.format("\\%02X", Integer.valueOf((int) c)));
                    } else {
                        escaped.append(c);
                    }
                    break;
            }
        }
        return escaped.toString();
    }

    /* Append one indented LLVM instruction to the current function body. */
    void emit(String line) {
        body.append("  ").append(line).append("\n");
    }

    /* Labels are not indented in LLVM IR. */
    void emitLabel(String label) {
        body.append(label).append(":\n");
    }

    /* Fresh temporary registers keep generated IR names unique. */
    String nextTemp() {
        return "%t" + tempCounter++;
    }

    /* Fresh labels keep branches readable and collision-free. */
    String nextLabel(String prefix) {
        return prefix + "." + labelCounter++;
    }

    /* Every variable must be assigned before it can be read. */
    VarInfo lookupVariable(String name) {
        VarInfo info = variables.get(name);
        if (info == null) {
            throw new RuntimeException("Undefined variable: " + name);
        }
        return info;
    }

    /* Reuse scalar slots, or allocate one when the variable first appears. */
    VarInfo ensureScalarVariable(String name) {
        VarInfo info = variables.get(name);
        if (info != null) {
            if (!info.type().isScalar()) {
                throw new RuntimeException("Variable " + name + " is not a scalar");
            }
            return info;
        }
        String ptr = "%" + name;
        emit(ptr + " = alloca i32");
        info = new VarInfo(name, TypeInfo.SCALAR, ptr);
        variables.put(name, info);
        return info;
    }

    /* Matrices keep a fixed shape after their first assignment. */
    VarInfo ensureMatrixVariable(String name, TypeInfo type) {
        VarInfo info = variables.get(name);
        if (info != null) {
            if (!info.type().sameShape(type)) {
                throw new RuntimeException("Matrix " + name + " changes shape during execution");
            }
            return info;
        }
        String ptr = "%" + name;
        emit(ptr + " = alloca [" + type.flatSize() + " x i32]");
        info = new VarInfo(name, type, ptr);
        variables.put(name, info);
        return info;
    }

    /* Temporary matrices hold intermediate expression results. */
    MatrixRef createTempMatrix(TypeInfo type) {
        String ptr = nextTemp();
        emit(ptr + " = alloca [" + type.flatSize() + " x i32]");
        return new MatrixRef(type, ptr);
    }

    /* Treat a stored variable as a matrix reference when its type allows it. */
    MatrixRef asMatrixRef(VarInfo info) {
        return new MatrixRef(info.type(), info.ptr());
    }

    /* Scalar assignment is just an i32 store. */
    void storeScalar(String name, String value) {
        VarInfo info = ensureScalarVariable(name);
        emit("store i32 " + value + ", ptr " + info.ptr());
    }

    /* Reading a scalar produces a fresh LLVM register. */
    String loadScalar(String name) {
        VarInfo info = lookupVariable(name);
        if (!info.type().isScalar()) {
            throw new RuntimeException("Variable " + name + " is not a scalar");
        }
        String reg = nextTemp();
        emit(reg + " = load i32, ptr " + info.ptr());
        return reg;
    }

    /* Matrix data is stored row-major in one flat LLVM array. */
    String emitConstMatrixElementPtr(MatrixRef matrix, int flatIndex) {
        String ptr = nextTemp();
        emit(ptr + " = getelementptr inbounds [" + matrix.type().flatSize() + " x i32], ptr "
            + matrix.ptr() + ", i32 0, i32 " + flatIndex);
        return ptr;
    }

    /* Runtime indexes are 1-based in the source language, like MATLAB. */
    String emitMatrixElementPtr(MatrixRef matrix, String rowValue, String colValue) {
        String rowZero = nextTemp();
        emit(rowZero + " = sub i32 " + rowValue + ", 1");
        String rowOffset = nextTemp();
        emit(rowOffset + " = mul i32 " + rowZero + ", " + matrix.type().cols());
        String colZero = nextTemp();
        emit(colZero + " = sub i32 " + colValue + ", 1");
        String flatIndex = nextTemp();
        emit(flatIndex + " = add i32 " + rowOffset + ", " + colZero);
        String ptr = nextTemp();
        emit(ptr + " = getelementptr inbounds [" + matrix.type().flatSize() + " x i32], ptr "
            + matrix.ptr() + ", i32 0, i32 " + flatIndex);
        return ptr;
    }

    /* Constant indexes are used when row and column are known while generating. */
    String loadConstMatrixElement(MatrixRef matrix, int row, int col) {
        int flatIndex = row * matrix.type().cols() + col;
        String ptr = emitConstMatrixElementPtr(matrix, flatIndex);
        String value = nextTemp();
        emit(value + " = load i32, ptr " + ptr);
        return value;
    }

    /* Dynamic indexes are used for expressions like E(i,j). */
    String loadMatrixElement(MatrixRef matrix, String rowValue, String colValue) {
        String ptr = emitMatrixElementPtr(matrix, rowValue, colValue);
        String value = nextTemp();
        emit(value + " = load i32, ptr " + ptr);
        return value;
    }

    /* Store into a known matrix position. */
    void storeConstMatrixElement(MatrixRef matrix, int row, int col, String value) {
        int flatIndex = row * matrix.type().cols() + col;
        String ptr = emitConstMatrixElementPtr(matrix, flatIndex);
        emit("store i32 " + value + ", ptr " + ptr);
    }

    /* Store into a matrix position computed at runtime. */
    void storeMatrixElement(MatrixRef matrix, String rowValue, String colValue, String value) {
        String ptr = emitMatrixElementPtr(matrix, rowValue, colValue);
        emit("store i32 " + value + ", ptr " + ptr);
    }

    /* Assignment to a matrix variable copies the whole matrix value. */
    MatrixRef copyIntoVariable(String name, MatrixRef source) {
        VarInfo info = ensureMatrixVariable(name, source.type());
        MatrixRef target = asMatrixRef(info);
        copyMatrix(source, target);
        return target;
    }

    /* Copy matrices element by element so assignments keep their own storage. */
    void copyMatrix(MatrixRef source, MatrixRef target) {
        if (!source.type().sameShape(target.type())) {
            throw new RuntimeException("Matrix copy between incompatible shapes");
        }
        for (int i = 0; i < source.type().rows(); i++) {
            for (int j = 0; j < source.type().cols(); j++) {
                String value = loadConstMatrixElement(source, i, j);
                storeConstMatrixElement(target, i, j, value);
            }
        }
    }

    /* Basic scalar arithmetic helpers. */
    String emitAdd(String left, String right) {
        String result = nextTemp();
        emit(result + " = add i32 " + left + ", " + right);
        return result;
    }

    /* Subtraction stays separate so matrix subtraction can reuse it. */
    String emitSub(String left, String right) {
        String result = nextTemp();
        emit(result + " = sub i32 " + left + ", " + right);
        return result;
    }

    /* Multiplication is shared by scalars and expanded matrix operations. */
    String emitMul(String left, String right) {
        String result = nextTemp();
        emit(result + " = mul i32 " + left + ", " + right);
        return result;
    }

    /* Comparisons produce 0 or 1 so they can also be used as scalar values. */
    String emitComparison(String op, String left, String right) {
        String cmp = nextTemp();
        String pred;
        if (">".equals(op)) {
            pred = "sgt";
        } else if ("<".equals(op)) {
            pred = "slt";
        } else if (">=".equals(op)) {
            pred = "sge";
        } else if ("<=".equals(op)) {
            pred = "sle";
        } else if ("==".equals(op)) {
            pred = "eq";
        } else if ("~=".equals(op)) {
            pred = "ne";
        } else {
            throw new RuntimeException("Unknown comparison operator: " + op);
        }
        emit(cmp + " = icmp " + pred + " i32 " + left + ", " + right);
        String asInt = nextTemp();
        emit(asInt + " = zext i1 " + cmp + " to i32");
        return asInt;
    }

    /* Turn a scalar into an LLVM i1 condition for branches. */
    String emitScalarCondition(String scalarValue) {
        String cond = nextTemp();
        emit(cond + " = icmp ne i32 " + scalarValue + ", 0");
        return cond;
    }

    /* Matrix operators are expanded into simple scalar loads and stores. */
    MatrixRef emitMatrixAdd(MatrixRef left, MatrixRef right, boolean subtract) {
        if (!left.type().sameShape(right.type())) {
            throw new RuntimeException("Matrix sizes do not match");
        }
        MatrixRef result = createTempMatrix(left.type());
        for (int i = 0; i < left.type().rows(); i++) {
            for (int j = 0; j < left.type().cols(); j++) {
                String a = loadConstMatrixElement(left, i, j);
                String b = loadConstMatrixElement(right, i, j);
                String value = subtract ? emitSub(a, b) : emitAdd(a, b);
                storeConstMatrixElement(result, i, j, value);
            }
        }
        return result;
    }

    /* Scalar times matrix, or matrix times scalar. */
    MatrixRef emitMatrixScale(MatrixRef matrix, String factor) {
        MatrixRef result = createTempMatrix(matrix.type());
        for (int i = 0; i < matrix.type().rows(); i++) {
            for (int j = 0; j < matrix.type().cols(); j++) {
                String value = loadConstMatrixElement(matrix, i, j);
                String scaled = emitMul(value, factor);
                storeConstMatrixElement(result, i, j, scaled);
            }
        }
        return result;
    }

    /* Matrix multiplication is expanded with the classic triple loop. */
    MatrixRef emitMatrixMultiply(MatrixRef left, MatrixRef right) {
        if (!left.type().isMatrix() || !right.type().isMatrix()) {
            throw new RuntimeException("Matrix multiplication needs matrices");
        }
        if (left.type().cols() != right.type().rows()) {
            throw new RuntimeException("Matrix sizes do not match for multiplication");
        }
        TypeInfo resultType = new TypeInfo(true, left.type().rows(), right.type().cols());
        MatrixRef result = createTempMatrix(resultType);
        for (int i = 0; i < resultType.rows(); i++) {
            for (int j = 0; j < resultType.cols(); j++) {
                String sum = null;
                for (int k = 0; k < left.type().cols(); k++) {
                    String a = loadConstMatrixElement(left, i, k);
                    String b = loadConstMatrixElement(right, k, j);
                    String product = emitMul(a, b);
                    if (sum == null) {
                        sum = product;
                    } else {
                        sum = emitAdd(sum, product);
                    }
                }
                storeConstMatrixElement(result, i, j, sum);
            }
        }
        return result;
    }

    /* printf handles numbers without adding a newline by itself. */
    void emitPrintf(CString format, String value) {
        String call = nextTemp();
        emit(call + " = call i32 (ptr, ...) @printf(ptr noundef " + format.gep() + ", i32 " + value + ")");
    }

    /* puts with the empty string gives a simple newline. */
    void emitBlankLine() {
        String call = nextTemp();
        emit(call + " = call i32 @puts(ptr noundef " + emptyLine.gep() + ")");
    }

    /* Start a disp block; simple variables get the MATLAB-style "X =" label. */
    void beginDisplay(String name) {
        if (displayCounter > 0) {
            emitBlankLine();
        }
        displayCounter++;
        if (name != null) {
            CString label = addCString(name + " =");
            String call = nextTemp();
            emit(call + " = call i32 @puts(ptr noundef " + label.gep() + ")");
        }
    }

    /* Scalars print on one line. */
    void printScalar(String value) {
        emitPrintf(fmtNum, value);
        emitBlankLine();
    }

    /* Matrices print row by row, with spaces between columns. */
    void printMatrix(MatrixRef matrix) {
        for (int i = 0; i < matrix.type().rows(); i++) {
            String first = loadConstMatrixElement(matrix, i, 0);
            emitPrintf(fmtNum, first);
            for (int j = 1; j < matrix.type().cols(); j++) {
                String next = loadConstMatrixElement(matrix, i, j);
                emitPrintf(fmtSpaceNum, next);
            }
            emitBlankLine();
        }
    }
}

/* 1- BASE CODE: normal assignment such as x = 5 or A = [1 2; 3 4]. */
final class AssignStmt extends Statement {
    private final String name;
    private final Expr expr;

    AssignStmt(String name, Expr expr) {
        this.name = name;
        this.expr = expr;
    }

    void generate(CodegenState state) {
        TypeInfo type = expr.type(state);
        if (type.isScalar()) {
            state.storeScalar(name, expr.emitScalar(state));
        } else {
            MatrixRef source = expr.emitMatrix(state);
            state.copyIntoVariable(name, source);
        }
    }
}

/* 1- BASE CODE: matrix cell assignment such as A(row,col) = value. */
final class MatrixAssignStmt extends Statement {
    private final String name;
    private final Expr rowExpr;
    private final Expr colExpr;
    private final Expr valueExpr;

    MatrixAssignStmt(String name, Expr rowExpr, Expr colExpr, Expr valueExpr) {
        this.name = name;
        this.rowExpr = rowExpr;
        this.colExpr = colExpr;
        this.valueExpr = valueExpr;
    }

    void generate(CodegenState state) {
        VarInfo info = state.lookupVariable(name);
        if (!info.type().isMatrix()) {
            throw new RuntimeException("Variable " + name + " is not a matrix");
        }
        String row = rowExpr.emitScalar(state);
        String col = colExpr.emitScalar(state);
        String value = valueExpr.emitScalar(state);
        state.storeMatrixElement(state.asMatrixRef(info), row, col, value);
    }
}

/* 1- BASE CODE: disp prints scalar or matrix results. */
final class DispStmt extends Statement {
    private final Expr expr;

    DispStmt(Expr expr) {
        this.expr = expr;
    }

    void generate(CodegenState state) {
        state.beginDisplay(expr.simpleName());
        if (expr.type(state).isScalar()) {
            state.printScalar(expr.emitScalar(state));
        } else {
            state.printMatrix(expr.emitMatrix(state));
        }
    }
}

/* 2- IF/FOR CODE: for loops lower to labels, branches, a step slot, and an end slot. */
final class ForStmt extends Statement {
    private final String variable;
    private final Expr startExpr;
    private final Expr endExpr;
    private final List body;

    ForStmt(String variable, Expr startExpr, Expr endExpr, List body) {
        this.variable = variable;
        this.startExpr = startExpr;
        this.endExpr = endExpr;
        this.body = body;
    }

    void generate(CodegenState state) {
        /* The loop supports both increasing and decreasing ranges. */
        VarInfo loopVar = state.ensureScalarVariable(variable);
        String startValue = startExpr.emitScalar(state);
        String endValue = endExpr.emitScalar(state);

        String endSlot = state.nextTemp();
        state.emit(endSlot + " = alloca i32");
        state.emit("store i32 " + endValue + ", ptr " + endSlot);

        String stepSlot = state.nextTemp();
        state.emit(stepSlot + " = alloca i32");

        state.emit("store i32 " + startValue + ", ptr " + loopVar.ptr());

        String chooseStep = state.nextTemp();
        state.emit(chooseStep + " = icmp sle i32 " + startValue + ", " + endValue);

        String posLabel = state.nextLabel("for.pos");
        String negLabel = state.nextLabel("for.neg");
        String checkLabel = state.nextLabel("for.check");
        String cmpPosLabel = state.nextLabel("for.cmp.pos");
        String cmpNegLabel = state.nextLabel("for.cmp.neg");
        String bodyLabel = state.nextLabel("for.body");
        String incLabel = state.nextLabel("for.inc");
        String endLabel = state.nextLabel("for.end");

        state.emit("br i1 " + chooseStep + ", label %" + posLabel + ", label %" + negLabel);

        state.emitLabel(posLabel);
        state.emit("store i32 1, ptr " + stepSlot);
        state.emit("br label %" + checkLabel);

        state.emitLabel(negLabel);
        state.emit("store i32 -1, ptr " + stepSlot);
        state.emit("br label %" + checkLabel);

        state.emitLabel(checkLabel);
        String current = state.nextTemp();
        state.emit(current + " = load i32, ptr " + loopVar.ptr());
        String finalValue = state.nextTemp();
        state.emit(finalValue + " = load i32, ptr " + endSlot);
        String stepValue = state.nextTemp();
        state.emit(stepValue + " = load i32, ptr " + stepSlot);
        String stepPositive = state.nextTemp();
        state.emit(stepPositive + " = icmp sge i32 " + stepValue + ", 0");
        state.emit("br i1 " + stepPositive + ", label %" + cmpPosLabel + ", label %" + cmpNegLabel);

        state.emitLabel(cmpPosLabel);
        String posCond = state.nextTemp();
        state.emit(posCond + " = icmp sle i32 " + current + ", " + finalValue);
        state.emit("br i1 " + posCond + ", label %" + bodyLabel + ", label %" + endLabel);

        state.emitLabel(cmpNegLabel);
        String negCond = state.nextTemp();
        state.emit(negCond + " = icmp sge i32 " + current + ", " + finalValue);
        state.emit("br i1 " + negCond + ", label %" + bodyLabel + ", label %" + endLabel);

        state.emitLabel(bodyLabel);
        for (int i = 0; i < body.size(); i++) {
            ((Statement) body.get(i)).generate(state);
        }
        state.emit("br label %" + incLabel);

        state.emitLabel(incLabel);
        String loopNow = state.nextTemp();
        state.emit(loopNow + " = load i32, ptr " + loopVar.ptr());
        String loopStep = state.nextTemp();
        state.emit(loopStep + " = load i32, ptr " + stepSlot);
        String nextValue = state.nextTemp();
        state.emit(nextValue + " = add i32 " + loopNow + ", " + loopStep);
        state.emit("store i32 " + nextValue + ", ptr " + loopVar.ptr());
        state.emit("br label %" + checkLabel);

        state.emitLabel(endLabel);
    }
}

/* 2- IF/FOR CODE: if/else lowers to then, else, and end labels. */
final class IfStmt extends Statement {
    private final Expr condition;
    private final List thenBlock;
    private final List elseBlock;

    IfStmt(Expr condition, List thenBlock, List elseBlock) {
        this.condition = condition;
        this.thenBlock = thenBlock;
        this.elseBlock = elseBlock;
    }

    void generate(CodegenState state) {
        String conditionValue = condition.emitScalar(state);
        String boolValue = state.emitScalarCondition(conditionValue);

        String thenLabel = state.nextLabel("if.then");
        String elseLabel = state.nextLabel("if.else");
        String endLabel = state.nextLabel("if.end");

        state.emit("br i1 " + boolValue + ", label %" + thenLabel + ", label %" + elseLabel);

        state.emitLabel(thenLabel);
        for (int i = 0; i < thenBlock.size(); i++) {
            ((Statement) thenBlock.get(i)).generate(state);
        }
        state.emit("br label %" + endLabel);

        state.emitLabel(elseLabel);
        for (int i = 0; i < elseBlock.size(); i++) {
            ((Statement) elseBlock.get(i)).generate(state);
        }
        state.emit("br label %" + endLabel);

        state.emitLabel(endLabel);
    }
}

/* 1- BASE CODE: integer literals are already scalar LLVM values. */
final class NumberExpr extends Expr {
    private final int value;

    NumberExpr(int value) {
        this.value = value;
    }

    TypeInfo type(CodegenState state) {
        return TypeInfo.SCALAR;
    }

    String emitScalar(CodegenState state) {
        return Integer.toString(value);
    }
}

/* 1- BASE CODE: variable expressions load scalars or reference matrix storage. */
final class VariableExpr extends Expr {
    private final String name;

    VariableExpr(String name) {
        this.name = name;
    }

    TypeInfo type(CodegenState state) {
        return state.lookupVariable(name).type();
    }

    String simpleName() {
        return name;
    }

    String emitScalar(CodegenState state) {
        return state.loadScalar(name);
    }

    MatrixRef emitMatrix(CodegenState state) {
        VarInfo info = state.lookupVariable(name);
        if (!info.type().isMatrix()) {
            throw new RuntimeException("Variable " + name + " is not a matrix");
        }
        return state.asMatrixRef(info);
    }
}

/* 1- BASE CODE: matrix literals allocate a temporary matrix and fill it cell by cell. */
final class MatrixLiteralExpr extends Expr {
    private final int[][] data;
    private final TypeInfo type;

    MatrixLiteralExpr(String raw) {
        data = parseMatrixData(raw);
        type = new TypeInfo(true, data.length, data[0].length);
    }

    TypeInfo type(CodegenState state) {
        return type;
    }

    MatrixRef emitMatrix(CodegenState state) {
        MatrixRef matrix = state.createTempMatrix(type);
        for (int i = 0; i < data.length; i++) {
            for (int j = 0; j < data[i].length; j++) {
                state.storeConstMatrixElement(matrix, i, j, Integer.toString(data[i][j]));
            }
        }
        return matrix;
    }

    /* The scanner gives us the inside of [ ... ]; this turns it into rows. */
    private static int[][] parseMatrixData(String raw) {
        String cleaned = raw.trim();
        if (cleaned.length() == 0) {
            throw new RuntimeException("Empty matrix literal");
        }

        String[] rowTexts = cleaned.split(";");
        List rows = new ArrayList();
        int width = -1;

        for (int i = 0; i < rowTexts.length; i++) {
            String normalized = rowTexts[i].trim();
            if (normalized.length() == 0) {
                continue;
            }
            String[] parts = normalized.split("[,\\s]+");
            int[] row = new int[parts.length];
            for (int j = 0; j < parts.length; j++) {
                row[j] = Integer.parseInt(parts[j]);
            }
            if (width == -1) {
                width = row.length;
            } else if (width != row.length) {
                throw new RuntimeException("Matrix rows must all have the same length");
            }
            rows.add(row);
        }

        if (rows.isEmpty()) {
            throw new RuntimeException("Empty matrix literal");
        }

        int[][] result = new int[rows.size()][width];
        for (int i = 0; i < rows.size(); i++) {
            System.arraycopy((int[]) rows.get(i), 0, result[i], 0, width);
        }
        return result;
    }
}

/* 1- BASE CODE: binary expressions cover arithmetic, comparisons, and matrix operations. */
final class BinaryExpr extends Expr {
    private final String op;
    private final Expr left;
    private final Expr right;

    BinaryExpr(String op, Expr left, Expr right) {
        this.op = op;
        this.left = left;
        this.right = right;
    }

    TypeInfo type(CodegenState state) {
        /* Decide result types before emitting IR, so invalid mixes fail early. */
        TypeInfo leftType = left.type(state);
        TypeInfo rightType = right.type(state);

        if ("+".equals(op) || "-".equals(op)) {
            if (leftType.isScalar() && rightType.isScalar()) {
                return TypeInfo.SCALAR;
            }
            if (leftType.isMatrix() && rightType.isMatrix() && leftType.sameShape(rightType)) {
                return leftType;
            }
        }

        if ("*".equals(op)) {
            if (leftType.isScalar() && rightType.isScalar()) {
                return TypeInfo.SCALAR;
            }
            if (leftType.isMatrix() && rightType.isMatrix()) {
                if (leftType.cols() != rightType.rows()) {
                    throw new RuntimeException("Matrix sizes do not match for multiplication");
                }
                return new TypeInfo(true, leftType.rows(), rightType.cols());
            }
            if (leftType.isScalar() && rightType.isMatrix()) {
                return rightType;
            }
            if (leftType.isMatrix() && rightType.isScalar()) {
                return leftType;
            }
        }

        if (">".equals(op) || "<".equals(op) || ">=".equals(op) || "<=".equals(op)
            || "==".equals(op) || "~=".equals(op)) {
            if (leftType.isScalar() && rightType.isScalar()) {
                return TypeInfo.SCALAR;
            }
        }

        throw new RuntimeException("Unsupported operands for operator " + op);
    }

    /* Emit scalar operators after type() confirms the result is scalar. */
    String emitScalar(CodegenState state) {
        if (!type(state).isScalar()) {
            throw new RuntimeException("Expression does not produce a scalar");
        }

        if ("+".equals(op)) {
            return state.emitAdd(left.emitScalar(state), right.emitScalar(state));
        }
        if ("-".equals(op)) {
            return state.emitSub(left.emitScalar(state), right.emitScalar(state));
        }
        if ("*".equals(op)) {
            return state.emitMul(left.emitScalar(state), right.emitScalar(state));
        }
        return state.emitComparison(op, left.emitScalar(state), right.emitScalar(state));
    }

    /* Emit matrix operators after type() confirms the result is a matrix. */
    MatrixRef emitMatrix(CodegenState state) {
        TypeInfo leftType = left.type(state);
        TypeInfo rightType = right.type(state);

        if ("+".equals(op)) {
            return state.emitMatrixAdd(left.emitMatrix(state), right.emitMatrix(state), false);
        }
        if ("-".equals(op)) {
            return state.emitMatrixAdd(left.emitMatrix(state), right.emitMatrix(state), true);
        }
        if ("*".equals(op)) {
            if (leftType.isMatrix() && rightType.isMatrix()) {
                return state.emitMatrixMultiply(left.emitMatrix(state), right.emitMatrix(state));
            }
            if (leftType.isScalar() && rightType.isMatrix()) {
                return state.emitMatrixScale(right.emitMatrix(state), left.emitScalar(state));
            }
            if (leftType.isMatrix() && rightType.isScalar()) {
                return state.emitMatrixScale(left.emitMatrix(state), right.emitScalar(state));
            }
        }
        throw new RuntimeException("Expression does not produce a matrix");
    }
}

/* 3- EXTRA CODE: read one matrix cell inside a larger expression, such as A(1,2) + 5. */
final class MatrixAccessExpr extends Expr {
    private final String name;
    private final Expr rowExpr;
    private final Expr colExpr;

    MatrixAccessExpr(String name, Expr rowExpr, Expr colExpr) {
        this.name = name;
        this.rowExpr = rowExpr;
        this.colExpr = colExpr;
    }

    TypeInfo type(CodegenState state) {
        return TypeInfo.SCALAR;
    }

    String emitScalar(CodegenState state) {
        VarInfo info = state.lookupVariable(name);
        if (!info.type().isMatrix()) {
            throw new RuntimeException("Variable " + name + " is not a matrix");
        }
        return state.loadMatrixElement(
            state.asMatrixRef(info),
            rowExpr.emitScalar(state),
            colExpr.emitScalar(state)
        );
    }
}
